### ISSUE TITLE
Client#create_backup method reverses return key/value pair in returned hash

### ISSUE THREAD

**Issue by demery** [upenn-libraries/stronghold#5]
The `#create_backup` method returns a hash of the Glacier archive ID and the archive's description. Archive ID should be the key and description the value, but it's reversed in the code:

https://github.com/upenn-libraries/stronghold/blob/master/lib/stronghold/client.rb#L43-L49

```ruby
# ...
backup_ids = {}
description = archive_description.nil? ? file_path : "#{archive_description}"
archive_id = create_archive(vault, file_path, description)
backup_ids[description] = archive_id
return backup_ids
```

It should be

```ruby
# ...
backup_ids[archive_id] = description
# ...
```

**Comment by kelynch** [comment]
Addressed in #6
